Repository googleinterns/step133-2020, pull requests merged in 2020-07, with the labels that each got.

#50 [Client] Created Parent Class for PageViews, PageDataHandler, ListDataHandler.
  src/main/webapp/js/datahandlers/listdatahandler.js
  src/main/webapp/js/datahandlers/scholarshipdatahandler.js
  src/main/webapp/js/datahandlers/scholarshiplistdatahandler.js
  src/main/webapp/js/datahandlers/singlepagedatahandler.js
  src/main/webapp/js/finscholar/collegepageview/collegepageview.js
  src/main/webapp/js/finscholar/commonlistview/commonlistview.js
  src/main/webapp/js/finscholar/navbar/navbar.js
  src/main/webapp/js/finscholar/scholarshippageview/scholarshippageview.js
  src/main/webapp/js/finscholar/singlepageview/singlepageview.js
Labels: enhancement

#86 [Bug]Fixes scroll list screen size issue and null pointer exception; changes table to list
  src/main/webapp/css/table.css
  src/main/webapp/js/basicview/basicview.soy
  src/main/webapp/js/datahandlers/collegelistdatahandler.js
  src/main/webapp/js/datahandlers/scholarshiplistdatahandler.js
  src/main/webapp/js/finscholar/commonlistview/commonlistview.js
  src/main/webapp/js/finscholar/commonlistview/commonlistview.soy
Labels: bug, enhancement

#82 [BUG] Add home page intro
  src/main/webapp/js/finscholar/homepagecontroller/homepagecontroller.soy
Labels: bug

#87 [Alpha]Implements Get Total Number
  src/main/java/com/google/step/finscholar/data/ServletConstantValues.java
  src/main/java/com/google/step/finscholar/servlets/DataSizeServlet.java
  src/main/webapp/js/datahandlers/collegelistdatahandler.js
  src/main/webapp/js/datahandlers/scholarshiplistdatahandler.js
  src/main/webapp/js/finscholar/commonlistview/commonlistview.js
  src/test/java/com/google/step/finscholar/firebase/FirebaseStorageManagerTest.java
Labels: enhancement

#85 Undefined printing of scholarship data fix
  src/main/webapp/js/datahandlers/scholarshipdatahandler.js
Labels: bug
